### ISSUE TITLE
Use this cookbook for FOSS4G-NA Dask workshop?

### ISSUE THREAD

**Issue by jsignell** [ProjectPythia/dask-cookbook#12]
I am going to be presenting a Dask workshop at [FOSS4G-NA 2](https://foss4gna.org/) (Free and Open Source Software for Geospatial, North America) in late October. It’s a 3 hour slot and I am planning on covering the basic concepts of Dask and touching on the rest of the Pangeo stack. I would like to build on existing work and store the final version somewhere that is group-owned.

This cookbook seems really great and I'd love to build off of it! Would you be open to me opening some PRs? My plan would be:

-  [x] Read through all the material and suggest updates
-  [ ] Potentially add a section on delayed/futures
-  [x] Update some language to make it less NCAR-specific (#13)
- ~Try to find a public option for how to run the tutorial without relying on binder~ EDIT: I just realized that project pythia has its own binder instance so maybe this is a non-issue

Just for context I also posted an issue about this on the [Pangeo discourse](https://discourse.pangeo.io/t/where-to-write-tutorial-content-for-dask-workshop-at-foss4g-na/3667)

**Comment by negin513** [comment]
Hello @jsignell , 

Thanks for your interest on contributing this. This is great! ;-) 

> Update some language to make it less NCAR-specific


I am open to all the ideas above. I can work on adding a section on delayed/futures if you are interest. 

> Update some language to make it less NCAR-specific

The materials from this cookbook came directly from [NCAR Dask Workshop](https://ncar.github.io/dask-tutorial/README.html), so that is why there is NCAR-specific languages, but I am 100% open to updating it.

**Comment by jsignell** [comment]
Yay!! I really like what you've got in here! I'll be taking a deeper look next week and you can expect some PRs to start rolling in :)

**Comment by negin513** [comment]
Hey @jukent Can you please add @jsignell as a collaborator to the repository? I am not the owner of this repos and cannot do this.

**Comment by jukent** [comment]
I've added @jsignell to the Pythia organization.

**Comment by jsignell** [comment]
Thanks @jukent! Do you mind giving me write access on this specific repo as well?

**Comment by jukent** [comment]
Done!

**Comment by negin513** [comment]
Hello @jsignell , 
I just wanted to reach out about this. Do you have any other contributions or PRs you want to make for the FOSS4GA-NA?

**Comment by jsignell** [comment]
Thank you! I am certainly not writing delayed/futures :sweat_smile: I intend to do a final look over tomorrow morning, so there might be one more PR but it'll just be any last typos or extra explanation.

**Comment by negin513** [comment]
Okay, I'll keep an eye out if you have a new PR, to review and merge it quickly. 

Aside from FOSS4GA-NA,  I think writing a section on delayed/futures might be beneficial for the community. Maybe after FOSS4GA we can have a quick meeting to discuss the time and effort required for it. (I know everyone is busy and that is the biggest limiting factor 😉 )

**Comment by jsignell** [comment]
Ok workshop is this afternoon! Thanks for your help with this
