### ISSUE TITLE
Write access?

### ISSUE THREAD

**Issue by jsignell** [ProjectPythia/dask-cookbook#14]
I am planning on presenting this at FOSS4G-NA and in that process I am going to be doing some tweaks over the next few weeks and it would be great to have write access to this repo. @andersy005, @jukent, or @brian-rose is that something that you have the power to grant?

@negin513 is :+1: on this idea.

**Comment by brian-rose** [comment]
Hi @jsignell it looks like you already do have write access to this repo!

Yes, I think any of the Pythia core team (including me) has power to add people but looks like someone already did this.

**Comment by jsignell** [comment]
Thanks yes! @jukent granted me it on #12!
